# Generated by Django 5.0.1 on 2024-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
