# Generated by Django 5.0.1 on 2024-03-28 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_customuser_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends_record',
            name='fid',
        ),
        migrations.AddField(
            model_name='friends_record',
            name='f_uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend_releted_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends_record',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friends_record',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
