# Generated by Django 5.0.1 on 2024-03-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_friends_record_fid_friends_record_f_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends_record',
            name='gid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.group'),
        ),
    ]
