# Generated by Django 5.0.1 on 2024-03-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_friends_record_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends_record',
            name='gid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.group'),
        ),
    ]
