# Generated by Django 5.0.1 on 2024-03-29 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_friends_record_composite_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_record',
            name='f_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_shared_with_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='gid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.group'),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
