# Generated by Django 5.0.1 on 2024-03-29 10:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_expense_record_f_uid_alter_expense_record_gid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense_record',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='expense_record',
            name='gid',
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 10, 4, 12, 729511, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='f_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expense_shared_with_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
