# Generated by Django 5.0.1 on 2024-03-29 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_rename_amount_expense_record_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense_record',
            old_name='uid',
            new_name='payer_uid',
        ),
        migrations.RenameField(
            model_name='expense_record',
            old_name='f_uid',
            new_name='shared_uid',
        ),
        migrations.AddField(
            model_name='expense_record',
            name='splited_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 10, 7, 17, 426247, tzinfo=datetime.timezone.utc)),
        ),
    ]
