# Generated by Django 5.0.1 on 2024-03-29 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_rename_uid_expense_record_payer_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends_record',
            name='owed_amount',
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 17, 24, 11, 534446, tzinfo=datetime.timezone.utc)),
        ),
    ]
