# Generated by Django 5.0.1 on 2024-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_remove_expense_record_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_record',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense_record',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
