# Generated by Django 5.0.1 on 2024-03-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_alter_expense_record_date_alter_expense_record_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense_record',
            old_name='date',
            new_name='date_field',
        ),
        migrations.RenameField(
            model_name='expense_record',
            old_name='time',
            new_name='time_field',
        ),
    ]
