# Generated by Django 5.0.1 on 2024-03-30 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_alter_expense_record_date_field_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friends_record',
            name='composite_primary_key',
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 3, 30), null=True),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 3, 30, 11, 43, 25, 777549), null=True),
        ),
        migrations.AddConstraint(
            model_name='friends_record',
            constraint=models.UniqueConstraint(fields=('uid', 'f_uid'), name='friends_composite_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='group_data',
            constraint=models.UniqueConstraint(fields=('gid', 'mid'), name='group_data_composite_primary_key'),
        ),
    ]
