# Generated by Django 5.0.1 on 2024-03-31 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_alter_expense_record_time_field_group_expense_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 4, 1), null=True),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 4, 27, 344016), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='gname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 4, 1), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 4, 27, 346012), null=True),
        ),
    ]
