# Generated by Django 5.0.1 on 2024-03-31 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_alter_expense_record_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 15, 16, 959990), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='gname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 15, 16, 962070), null=True),
        ),
    ]
