# Generated by Django 5.0.1 on 2024-03-31 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_alter_expense_record_time_field_alter_group_gname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 16, 23, 865009), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='gname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 16, 23, 867008), null=True),
        ),
    ]
