# Generated by Django 5.0.1 on 2024-03-31 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_alter_expense_record_time_field_alter_group_gname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 17, 36, 378495), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 0, 17, 36, 380495), null=True),
        ),
    ]
